version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      
  stripe:
    image: "stripe/stripe-cli:latest"
    network_mode: host
    command:
        listen --forward-to localhost:8080/api/stripe/webhook

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: kubilay41
